- name: Fetch frontend package from AWS CodeArtifact
  command: >
    aws codeartifact get-package-version-asset --domain {{ aws_codeartifact_domain }} --repository {{ aws_codeartifact_repo }} --region {{ aws_region }} --package class_schedule_frontend --package-version 0.1.0 --asset package.tgz --format npm /home/ec2-user/frontend-app.tgz

