- name: Create application directory
  file:
    path: /opt/app
    state: directory
    mode: "0755"
- name: Extract downloaded package
  unarchive:
    src: /home/ec2-user/frontend-app.tgz
    dest: /opt/app
    remote_src: yes
- name: Install npm dependencies
  shell: "node --max-old-space-size=802 $(which npm) install"
  args:
    chdir: /opt/app/package
- name: Build the frontend application
  shell: "npm run build"
  args:
    chdir: /opt/app/package
- name: Create systemd service for frontend app
  copy:
    dest: /etc/systemd/system/frontend-app.service
    content: |
      [Unit]
      Description=Node.js Frontend Application
      After=network.target

      [Service]
      ExecStart=/usr/bin/npm start
      WorkingDirectory=/opt/app/package
      Restart=always
      User=nobody
      Environment=REACT_APP_API_BASE_URL=http://{{ api_ip }}:8080

      [Install]
      WantedBy=multi-user.target
- name: Reload systemd to register new service
  command: systemctl daemon-reload
- name: Enable frontend application service
  systemd:
    name: frontend-app
    enabled: yes
- name: Start frontend application service
  systemd:
    name: frontend-app
    state: started
