- name: Install Tomcat 9
  hosts: all
  become: yes
  tasks:
    - name: Create Tomcat Directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: "0755"

    - name: Create Tomcat user
      user:
        name: tomcat
        shell: /bin/false
        home: /opt/tomcat

    - name: Download Tomcat 9.0.93
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz"
        dest: "/tmp/apache-tomcat-9.0.93.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-9.0.93.tar.gz"
        dest: /opt
        remote_src: yes
        owner: tomcat
        group: tomcat

    - name: Create symbolic link for Tomcat
      file:
        src: "/opt/apache-tomcat-9.0.93"
        dest: /opt/tomcat
        state: link
        owner: tomcat
        group: tomcat

    - name: Make catalina.sh executable
      file:
        path: /opt/tomcat/bin/catalina.sh
        mode: "0755"
        owner: tomcat
        group: tomcat

    - name: Create webapps directory
      file:
        path: /opt/tomcat/webapps
        state: directory
        owner: tomcat
        group: tomcat
        mode: "0755"